export const SERVICES_DATA = [
  {
    id: 1,
    name: "Master Electrician",
    provider: "John Williams",
    category: "Electrical",
    rating: 4.8,
    reviews: 158,
    priceRange: "$80-150/hr",
  },
  {
    id: 2,
    name: "Professional Plumber",
    provider: "Mike Johnson",
    category: "Plumbing",
    rating: 4.9,
    reviews: 243,
    priceRange: "$60-120/hr",
  },
  {
    id: 3,
    name: "Expert Painter",
    provider: "Sarah Davis",
    category: "Painting",
    rating: 4.7,
    reviews: 182,
    priceRange: "$50-100/hr",
  },
  {
    id: 4,
    name: "HVAC Specialist",
    provider: "Robert Brown",
    category: "HVAC",
    rating: 4.8,
    reviews: 167,
    priceRange: "$90-160/hr",
  },
  {
    id: 5,
    name: "Skilled Carpenter",
    provider: "James Wilson",
    category: "Carpentry",
    rating: 4.9,
    reviews: 201,
    priceRange: "$70-130/hr",
  },
  {
    id: 6,
    name: "Roofing Contractor",
    provider: "David Garcia",
    category: "Roofing",
    rating: 4.6,
    reviews: 95,
    priceRange: "$100-200/hr",
  },
  {
    id: 7,
    name: "Locksmith Expert",
    provider: "Tom Martinez",
    category: "Locksmith",
    rating: 4.9,
    reviews: 134,
    priceRange: "$40-80/hr",
  },
  {
    id: 8,
    name: "Landscaping Pro",
    provider: "Miguel Rodriguez",
    category: "Landscaping",
    rating: 4.7,
    reviews: 176,
    priceRange: "$55-110/hr",
  },
  {
    id: 9,
    name: "Tile Installation",
    provider: "Anthony Taylor",
    category: "Flooring",
    rating: 4.8,
    reviews: 119,
    priceRange: "$65-125/hr",
  },
  {
    id: 10,
    name: "Appliance Repair",
    provider: "Charles Anderson",
    category: "Appliances",
    rating: 4.9,
    reviews: 289,
    priceRange: "$75-140/hr",
  },
  {
    id: 11,
    name: "Drywall Expert",
    provider: "Richard Thomas",
    category: "Drywall",
    rating: 4.6,
    reviews: 87,
    priceRange: "$45-90/hr",
  },
  {
    id: 12,
    name: "Concrete Specialist",
    provider: "Joseph Moore",
    category: "Concrete",
    rating: 4.8,
    reviews: 156,
    priceRange: "$85-150/hr",
  },
  {
    id: 13,
    name: "Window Cleaning",
    provider: "Christopher Jackson",
    category: "Cleaning",
    rating: 4.9,
    reviews: 267,
    priceRange: "$30-70/hr",
  },
  {
    id: 14,
    name: "General Contractor",
    provider: "Daniel White",
    category: "General",
    rating: 4.7,
    reviews: 198,
    priceRange: "$95-180/hr",
  },
  {
    id: 15,
    name: "Kitchen Cabinet Specialist",
    provider: "Kenneth Harris",
    category: "Cabinetry",
    rating: 4.8,
    reviews: 143,
    priceRange: "$70-140/hr",
  },
  {
    id: 16,
    name: "Bathroom Renovator",
    provider: "Steven Martin",
    category: "Renovation",
    rating: 4.9,
    reviews: 215,
    priceRange: "$80-160/hr",
  },
  {
    id: 17,
    name: "Tree Trimming Service",
    provider: "Paul Thompson",
    category: "Landscaping",
    rating: 4.7,
    reviews: 164,
    priceRange: "$50-120/hr",
  },
  {
    id: 18,
    name: "Deck Builder",
    provider: "Mark Garcia",
    category: "Carpentry",
    rating: 4.8,
    reviews: 131,
    priceRange: "$75-145/hr",
  },
  {
    id: 19,
    name: "Fence Installation",
    provider: "Donald Miller",
    category: "Fencing",
    rating: 4.6,
    reviews: 102,
    priceRange: "$60-110/hr",
  },
  {
    id: 20,
    name: "Gutter Cleaning",
    provider: "George Davis",
    category: "Cleaning",
    rating: 4.9,
    reviews: 278,
    priceRange: "$35-80/hr",
  },
  {
    id: 21,
    name: "Wall Insulation",
    provider: "Kenneth Rodriguez",
    category: "Insulation",
    rating: 4.8,
    reviews: 111,
    priceRange: "$55-100/hr",
  },
  {
    id: 22,
    name: "Door Installation",
    provider: "Steven Lewis",
    category: "Doors",
    rating: 4.7,
    reviews: 153,
    priceRange: "$65-125/hr",
  },
  {
    id: 23,
    name: "Welding Services",
    provider: "Paul Walker",
    category: "Metal Work",
    rating: 4.9,
    reviews: 97,
    priceRange: "$70-140/hr",
  },
  {
    id: 24,
    name: "Pressure Washing",
    provider: "Mark Hall",
    category: "Cleaning",
    rating: 4.8,
    reviews: 291,
    priceRange: "$40-90/hr",
  },
  {
    id: 25,
    name: "Masonry Work",
    provider: "Donald Young",
    category: "Masonry",
    rating: 4.7,
    reviews: 127,
    priceRange: "$60-120/hr",
  },
  {
    id: 26,
    name: "Demolition Specialist",
    provider: "George King",
    category: "Demolition",
    rating: 4.6,
    reviews: 68,
    priceRange: "$100-180/hr",
  },
  {
    id: 27,
    name: "Siding Contractor",
    provider: "Kenneth Wright",
    category: "Siding",
    rating: 4.8,
    reviews: 145,
    priceRange: "$75-135/hr",
  },
  {
    id: 28,
    name: "Pool Maintenance",
    provider: "Steven Lopez",
    category: "Pools",
    rating: 4.9,
    reviews: 203,
    priceRange: "$50-100/hr",
  },
  {
    id: 29,
    name: "Attic Insulation",
    provider: "Paul Scott",
    category: "Insulation",
    rating: 4.8,
    reviews: 138,
    priceRange: "$55-110/hr",
  },
  {
    id: 30,
    name: "Garage Door Repair",
    provider: "Mark Green",
    category: "Garage",
    rating: 4.7,
    reviews: 172,
    priceRange: "$65-130/hr",
  },
];
